### ISSUE TITLE
Pip installation bug

### ISSUE THREAD

**Issue by tagirshin** [chython/chython#14]
I tried to install the package via pip (not the DEV version) and encountered an error related to `setuptools`. The error looks like this:
<img width="1375" alt="setuptools bug" src="https://user-images.githubusercontent.com/17476642/136753624-b7b1987c-07e1-4673-81a8-f6eec000b251.png">

I found that [downgrading](https://stackoverflow.com/questions/60896576/unable-to-install-the-new-tflite-support-using-pip) `setuptools` to version 41 solves problem. And it really worked out.

**Comment by stsouko** [comment]
looks like a problem in setuptools and cython
