### ISSUE TITLE
linear fp bug

### ISSUE THREAD

**Issue by stsouko** [chython/chython#39]
@TimurGimadiev 
linear_hash_smiles number_bit_pairs=0 is brocken

**Comment by TimurGimadiev** [comment]
and smiles letter do not converted to capitals
 {'c:c:c:c': 4,
 'NC': 2,
 'c:c': 4,
 'c:cC': 4,
 'c': 4,
 'OC': 4,
 'CC': 4,
 'COc': 3,
 'NCc:c': 2,
 'c:cOC': 4,
 'Oc:c:c': 4,
 'c:c:c': 4,
 'NCC': 2,
 'Oc:c': 4,
 'CNC': 1,
 'N': 1,
 'O': 3,
 'c:c:cC': 4,
 'CCc': 1,
 'c:cCC': 2,
 'OCc': 1,
 'OCc:c': 2,
 'Oc:cO': 1,
 'cOCc': 1,
 'NCCc': 1,
 'CNCC': 2}
